
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install -r python2-6-requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION > 2.6 ]]; then pip install -r opt_requirements.txt; fi
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pyflakes .; fi
  - if [[ $TRAVIS_PYTHON_VERSION > 2.6 ]]; then flake8 .; fi
script: nosetests -v --cover-erase --with-coverage --cover-package=novaagent
