
language: python
before_script:
  - flake8 .
script:
  - nosetests -v --cover-erase --with-coverage --cover-package=novaagent

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - TYPE='pypi'
  - TYPE='distro'
  - TYPE='nosystemd'

dist: xenial

install:
  - env
  - pip install -e .[tests]
  - sudo apt update -qq
  - [ "$TYPE" == "pypi" ] && sudo apt install libsystemd-dev
  - [ "$TYPE" == "pypi" ] && pip install -e .[systemd]
  - [ "$TYPE" == "distro" ] && sudo apt install python-systemd python3-systemd
