
language: python
before_script:
  - flake8 .
script:
  - nosetests -v --cover-erase --with-coverage --cover-package=novaagent

matrix:
  include:
    # PyPI systemd
    - dist: xenial
      env:
        - TYPE='xenial-systemd-pypi'
      python:
        - "2.7"
        - "3.4"
        - "3.5"
        - "3.6"
      install:
        - sudo apt update -qq
        - sudo apt install libsystemd-dev
        - pip install -e .[systemd]
        - pip install -e .[tests]
    # System systemd
    - dist: xenial
      env:
        - TYPE='xenial-systemd-distro'
      python:
        - "2.7"
        - "3.5"
      install:
        - sudo apt update -qq
        - sudo apt install python-systemd python3-systemd
        - pip install -e .[tests]
    # No systemd
    - dist: trusty
      env:
        - TYPE='trusty-nosystemd'
      python:
        - "2.6"
        - "2.7"
        - "3.4"
        - "3.5"
        - "3.6"
      install:
        - pip install -e .[tests]
